### ISSUE TITLE
図の中で文献を引用すると文献番号ではなく図番号が振られてしまう

### ISSUE THREAD

**Issue by zushi0516** [ut-khanlab/master_thesis_template_for_typst#3]
```
#img(
  image("path"),
  caption: [
  caption @paper
    ],
) <figure1>
```

のように図を書くと、@paperの部分が文献番号ではなく図番号になってしまいます。

**Comment by chantakan** [comment]
Could you please tell me a bit more about this?
There doesn't seem to be any problems in my environment.

**Comment by chantakan** [comment]
I got it! if you cite a reference on a figure, the numbering is preferred.
I added the following to-string function with reference to [this issue](https://github.com/typst/typst/issues/2196#issuecomment-1728135476)
```
#let to-string(content) = {
  if content.has("text") {
    content.text
  } else if content.has("children") {
    content.children.map(to-string).join("")
  } else if content.has("body") {
    to-string(content.body)
  } else if content == [ ] {
    " "
  }
}
```
