### ISSUE TITLE
quillを使って量子回路を描くと回路の中に式番号が振られてしまう&キャプションが変な位置に出る

### ISSUE THREAD

**Issue by soichiro524** [ut-khanlab/master_thesis_template_for_typst#6]
[quillパッケージ](https://github.com/typst/packages/tree/main/packages/preview/quill/0.2.0)を用いて量子回路を以下のように描くと、
```
#img(
  {
  quantum-circuit(
    lstick($|0〉$), gate($H$), ctrl(1), 1 , [\ ],
    lstick($|0〉$), 1, targ(), 1
  )
}
)
```
以下のように `lstick`の箇所に式番号が振られてしまいます。また、キャプションも変な位置に出てしまいます。
何か解決方法はありますでしょうか？
（`template.typ` の `set math.equation(supplement: [式], numbering: equation_num)` をコメントアウトすれば式番号は消えるんですが、式番号全てが消えてしまうので...）
![quill](https://github.com/ut-khanlab/master_thesis_template_for_typst/assets/130641052/0eeae790-a139-43e4-a0b3-3950f70c93b7)

**Comment by chantakan** [comment]
## 回路の中に式番号が振られてしまう
これはqill v0.3.0以降解消されているそうです.

## キャプションが変な位置に出る
これは量子回路を画像と認識しておらず、captionの横に表示されてしまっているためです。
9b77a84562ecf83c4100fa17a1980fa432c302a2 で画像以外のcontentをimgに入れられるようにしました。
